# Site settings
title: New Blog

#author:
#  name: AH
#  email: lol@gmail.com
  
#description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima

minima:
  skin: dark
  
